### PR TITLE
added my card

### PR DESCRIPTION
**Pull request by eswarupkumar**
Hey ! I added my card into the list. Please have a check.

### CODE REVIEW

**Review by tavolafourcade — CHANGES_REQUESTED** [review]
Hello there! Please update your current repo with the current HacktoberFestChallenge Branch since you're committing over the first version but there are changes made and other people collaborated so you basically are overridden their work lol. 

Once you make the pull request, update it with your changes and then make the push to the HacktoberFestChallenge branch.

**Comment by eswarupkumar** [comment]
Hey, could you check now. Is it fine now?

**Review by eswarupkumar — COMMENTED** [review]
Done perhaps.

**Review by tavolafourcade — APPROVED** [review]
I made some minor changes as adding a new class

**Pull request merged**
